import { BarberProfile } from '../types/barber.types';
import { Post, PostType } from '../types/post.types';
import { PromotionTier } from '../types/promotion.types';

// Mock data for development - will be replaced with API calls
export const MOCK_BARBERS: BarberProfile[] = [
  {
    id: '1',
    userId: 'user1',
    displayName: 'Mike The Barber',
    firstName: 'Mike',
    lastName: 'Johnson',
    bio: 'Master Barber with 15+ years experience. Specializing in precision fades and beard sculpting. Making people look their best, one cut at a time! 💈',
    profileImage: undefined,
    coverImage: undefined,
    specialties: ['Fades', 'Beard Trim', 'Line Up', 'Hot Towel Shave'],
    yearsOfExperience: 15,
    certifications: ['Master Barber License', 'Advanced Fade Techniques'],
    location: {
      latitude: 37.7749,
      longitude: -122.4194,
      address: '123 Main St',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
    },
    worksAt: 'Elite Cuts Barbershop',
    followersCount: 12500,
    followingCount: 450,
    postsCount: 234,
    rating: 4.9,
    totalReviews: 456,
    totalClients: 2300,
    services: [
      { id: 's1', name: 'Signature Fade', description: 'Perfect fade every time', duration: 45, price: 45, category: 'haircut', isPopular: true },
      { id: 's2', name: 'Beard Trim & Shape', duration: 30, price: 30, category: 'beard' },
      { id: 's3', name: 'Hot Towel Shave', duration: 45, price: 50, category: 'beard' },
    ],
    isAvailable: true,
    acceptsWalkIns: false,
    instantBooking: true,
    isVerified: true,
    promotionTier: PromotionTier.GOLD,
    joinedDate: '2020-01-15',
    themeColor: '#D4AF37',
    pageLayout: 'modern',
    portfolioImages: [],
    featuredWork: [],
    responseTime: 'Within 1 hour',
    responseRate: 98,
  },
  {
    id: '2',
    userId: 'user2',
    displayName: 'Fade King',
    firstName: 'Marcus',
    lastName: 'Williams',
    bio: '🏆 Award-winning barber | Fade specialist | Book your appointment now!',
    profileImage: undefined,
    coverImage: undefined,
    specialties: ['Bald Fade', 'Taper', 'Kids Haircuts'],
    yearsOfExperience: 10,
    certifications: ['Licensed Barber'],
    location: {
      latitude: 37.7849,
      longitude: -122.4094,
      address: '456 Market St',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94103',
      country: 'USA',
    },
    followersCount: 8900,
    followingCount: 320,
    postsCount: 178,
    rating: 4.8,
    totalReviews: 312,
    totalClients: 1800,
    services: [
      { id: 's4', name: 'Premium Fade', duration: 40, price: 40, category: 'haircut', isPopular: true },
      { id: 's5', name: 'Kids Cut', duration: 30, price: 25, category: 'haircut' },
    ],
    isAvailable: true,
    acceptsWalkIns: true,
    instantBooking: true,
    isVerified: true,
    promotionTier: PromotionTier.SILVER,
    joinedDate: '2021-03-20',
    portfolioImages: [],
    featuredWork: [],
    responseTime: 'Within 2 hours',
    responseRate: 95,
  },
  {
    id: '3',
    userId: 'user3',
    displayName: 'Beard Master',
    firstName: 'David',
    lastName: 'Chen',
    bio: 'Beard specialist and traditional barber. Using time-honored techniques with modern style.',
    profileImage: undefined,
    coverImage: undefined,
    specialties: ['Beard Sculpting', 'Hot Towel Shave', 'Hair Coloring'],
    yearsOfExperience: 12,
    certifications: ['Master Barber', 'Color Specialist'],
    location: {
      latitude: 37.7649,
      longitude: -122.4294,
      address: '789 Valencia St',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94110',
      country: 'USA',
    },
    followersCount: 6700,
    followingCount: 180,
    postsCount: 145,
    rating: 4.9,
    totalReviews: 267,
    totalClients: 1500,
    services: [
      { id: 's6', name: 'Royal Shave', duration: 60, price: 65, category: 'beard', isPopular: true },
      { id: 's7', name: 'Beard Sculpt', duration: 45, price: 45, category: 'beard' },
    ],
    isAvailable: false,
    acceptsWalkIns: false,
    instantBooking: false,
    isVerified: false,
    promotionTier: PromotionTier.BRONZE,
    joinedDate: '2021-06-10',
    portfolioImages: [],
    featuredWork: [],
    responseTime: 'Within 4 hours',
    responseRate: 90,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    authorId: '1',
    authorName: 'Mike The Barber',
    authorAvatar: undefined,
    authorRole: 'BARBER',
    isVerified: true,
    promotionTier: PromotionTier.GOLD,
    type: PostType.TRANSFORMATION,
    caption: 'Fresh fade transformation! From grown out to sharp and clean. 🔥✂️ #FadeGame #BarberLife #Transformation',
    hashtags: ['FadeGame', 'BarberLife', 'Transformation'],
    mentions: [],
    media: [{ id: 'm1', type: 'image', url: 'https://via.placeholder.com/400' }],
    likesCount: 1234,
    commentsCount: 89,
    sharesCount: 45,
    savesCount: 234,
    viewsCount: 5678,
    isLiked: false,
    isSaved: false,
    location: { name: 'Elite Cuts Barbershop, San Francisco' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    authorId: '2',
    authorName: 'Fade King',
    authorAvatar: undefined,
    authorRole: 'BARBER',
    isVerified: true,
    promotionTier: PromotionTier.SILVER,
    type: PostType.VIDEO,
    caption: 'Bald fade tutorial - watch how I blend it perfectly! Drop a 🔥 if you learned something!',
    hashtags: ['Tutorial', 'BaldFade', 'BarberTutorial'],
    mentions: [],
    media: [{ id: 'm2', type: 'video', url: 'https://via.placeholder.com/400', duration: 45 }],
    likesCount: 2145,
    commentsCount: 156,
    sharesCount: 234,
    savesCount: 456,
    viewsCount: 12340,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];
